using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class EndModel
{
    [RealtimeProperty(1, true, true)]
    private double _endTime = -1;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class EndModel : RealtimeModel {
    public double endTime {
        get {
            return _cache.LookForValueInCache(_endTime, entry => entry.endTimeSet, entry => entry.endTime);
        }
        set {
            if (this.endTime == value) return;
            _cache.UpdateLocalCache(entry => { entry.endTimeSet = true; entry.endTime = value; return entry; });
            InvalidateReliableLength();
            FireEndTimeDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(EndModel model, T value);
    public event PropertyChangedHandler<double> endTimeDidChange;
    
    private struct LocalCacheEntry {
        public bool endTimeSet;
        public double endTime;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        EndTime = 1,
    }
    
    public EndModel() : this(null) {
    }
    
    public EndModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireEndTimeDidChange(double value) {
        try {
            endTimeDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteDoubleLength((uint)PropertyID.EndTime);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.endTimeSet) {
                length += WriteStream.WriteDoubleLength((uint)PropertyID.EndTime);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteDouble((uint)PropertyID.EndTime, _endTime);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.endTimeSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.endTimeSet) {
                stream.WriteDouble((uint)PropertyID.EndTime, entry.endTime);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.EndTime: {
                    double previousValue = _endTime;
                    _endTime = stream.ReadDouble();
                    bool endTimeExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.endTimeSet);
                    if (!endTimeExistsInChangeCache && _endTime != previousValue) {
                        FireEndTimeDidChange(_endTime);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _endTime = endTime;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
